v1.1.2 push

diff --git a/hArch b/hArch
--- a/hArch
+++ b/hArch
@@ -6,8 +6,11 @@
 # Author    : Binary-Brawler                                     |
 # Github    : github.com/Binary-Brawler                          |
 # LinkedIn  : linkedin.com/in/brandon-walker-0b0542116/          |
-# Version   : 1.0.2                                              |
-# Intent    : Simplistic Linux box for Red Teaming/Pentesting    | 
+# Version   : 1.1.2                                              |
+# Intent    : Simplistic Linux box for Red Teaming/Pentesting    |
+#               - BlackArch Repo (Access to tools)               |
+#               - lightwieght distro for older machines          |
+#               - vimrc/nvim/vscode (for coders)
 # ---------------------------------------------------------------
 
 # Constants
@@ -26,22 +29,14 @@ log_error() { echo -e "[${RED}ERROR${RESET}] $1"; }
 print_info() { echo -e "[${GREEN}INFO${RESET}] $1${NEWLINE}"; }
 log_success() { echo -e "[SUCCESS] $1"; }
 
-# Repeats turned into functions ;) 
-sleep_and_clear() {
+function slear {
     sleep 3
     clear
 }
 
-# User Input
-prompt_for_input() {
-    read -p "$1" response
-    echo "$response"
-}
-
-# Simple greeter function
-greet() {
-    sleep_and_clear
-	echo -e "${PURPLE}Binary-Brawler's hArch Installer${RESET}"
+function greeter {
+    slear
+	echo -e "${PURPLE}Hackers Arch Installer${RESET}"
 	echo ${NEWLINE}
 	echo ${NEWLINE}
     echo "-------------------------------------------------------------------------------------------------"
@@ -64,19 +59,16 @@ greet() {
     echo "-------------------------------------------------------------------------------------------------"
 }
 
-# Check Internet Connection
-checkNet() {
+function check_Net {
     echo "---------------------------------------"
     print_info "Checking Internet Connection..."
     
-    # Check if speedtest-cli is installed
     if ! command -v speedtest-cli &>/dev/null; then
         print_info "speedtest-cli is not installed. Installing..."
         pacman -Sy >/dev/null
         python3 -m venv speedTest && cd speedTest/bin/ && ./pip3 install speedtest-cli >/dev/null
     fi
     
-    # Perform speed test
     print_info "Calculating Internet Speed..."
     sleep 1
     local speed=$(./speedtest-cli --simple | awk '/^Download:/ {print $2}')
@@ -84,8 +76,7 @@ checkNet() {
     echo "------------------------------------"
     print_info "Download Speed: $speed Mbps"
     echo "------------------------------------"
-    
-    # Check if download speed is greater than 50 Mbps
+
     if (( $(echo "$speed > 50" | bc -l) )); then
         print_info "Enabling Parallel Downloads..."
         sed -i '/#ParallelDownloads/s/^#//g' /etc/pacman.conf
@@ -98,9 +89,9 @@ checkNet() {
 
 # Calculate Swap Size Based on System RAM
 # Improve this...
-calculate_swap_size() {
+function calculate_Swap_Size {
     local ram_gb=$(free -g | awk '/^Mem:/{print $2}')
-    local swap_size="4G" # Default
+    local swap_size="2G"
 
     if [[ ! $ram_gb =~ ^[0-9]+$ ]]; then
         log_error "Error: Could not determine RAM size." >&2
@@ -108,10 +99,9 @@ calculate_swap_size() {
     fi
 
     if ((ram_gb < 2)); then
-        log_error "Error: Insufficient RAM (< 2GB)." >&2
-        exit 1
+        swap_size="${ram_gb}"
     elif ((ram_gb < 4)); then
-        swap_size="${ram_gb}G"
+        swap_size="3G"
     elif ((ram_gb < 16)); then
         swap_size="4G"
     else
@@ -121,60 +111,54 @@ calculate_swap_size() {
     echo "$swap_size"
 }
 
-# Partitioning Function
-partition_drive() {
+function partition_Drive {
     local drive="$1"
     local swap_size=$(calculate_swap_size)
     local cmd_list=()
 
     if [[ -d "/sys/firmware/efi/efivars/" ]]; then
         cmd_list=(
-            "g"                          # Create a new GPT table
-            "n" "" "" "+512M"            # EFI partition
-            "n" "" "" "+$swap_size"      # Swap partition
-            "n" "" "" ""                 # Root partition
-            "t" "1" "1"                  # Set type of EFI partition to EFI System
-            "t" "2" "19"                 # Set type of swap to Linux swap
-            "w"                          # Write changes
+            "g"                          
+            "n" "" "" "+512M"            
+            "n" "" "" "+$swap_size"      
+            "n" "" "" ""                 
+            "t" "1" "1"                  
+            "t" "2" "19"                 
+            "w"                          
         )
 
     else
         cmd_list=(
-            "o" "n" "p" "" "" "+$swap_size"   # Swap partition
-            "n" "p" "" "" ""                  # Root partition
-            "t" "1" "82"                      # Set type of first partition to Linux swap
-            "w"                               # Write changes
+            "o" "n" "p" "" "" "+$swap_size"   
+            "n" "p" "" "" ""                  
+            "t" "1" "82"                      
+            "w"                               
         )
 
     fi
 
-    # Run fdisk commands
     printf "%s\n" "${cmd_list[@]}" | fdisk "$drive" >/dev/null 2>&1
 
-    # Check for fdisk errors
     if [[ $? -ne 0 ]]; then
         echo "Error: Failed to partition the drive."
         return 1
     fi
 
-    # Format partitions and mount them
     if [[ -d "/sys/firmware/efi/efivars/" ]]; then
         if [[ $drive == *nvme* ]]; then
-            mkfs.fat -F32 "${drive}p1" # Format EFI partition
-            mkswap "${drive}p2"         # Format swap partition
-            mkfs.ext4 "${drive}p3"      # Format root partition
+            mkfs.fat -F32 "${drive}p1" 
+            mkswap "${drive}p2"         
+            mkfs.ext4 "${drive}p3"      
 
-            # Mount partitions
             mount "${drive}p3" /mnt
             mkdir -p /mnt/boot/EFI
             mount "${drive}p1" /mnt/boot/EFI
             swapon "${drive}p2"
         elif [[ $drive == *sd* ]]; then
-            mkfs.fat -F32 "${drive}1" # Format EFI partition
-            mkswap "${drive}2"         # Format swap partition
-            mkfs.ext4 "${drive}3"      # Format root partition
+            mkfs.fat -F32 "${drive}1" 
+            mkswap "${drive}2"         
+            mkfs.ext4 "${drive}3"      
 
-            # Mount partitions
             mount "${drive}3" /mnt
             mkdir -p /mnt/boot/EFI
             mount "${drive}1" /mnt/boot/EFI
@@ -185,10 +169,9 @@ partition_drive() {
         fi
     else
         if [[ $drive == *sd* ]]; then
-            mkswap "${drive}1"         # Format swap partition
-            mkfs.ext4 "${drive}2"      # Format root partition
+            mkswap "${drive}1"         
+            mkfs.ext4 "${drive}2"      
 
-            # Mount partitions
             swapon "${drive}1"
             mount "${drive}2" /mnt
         else
@@ -198,19 +181,16 @@ partition_drive() {
     fi
 }
 
-# Installer Function
-installer() {
+function installer {
     echo "--------------------------------"
     print_info "Installing Arch base..."
     sleep 2
     pacstrap /mnt base base-devel linux linux-firmware vi vim nano dhcpcd iwd >/dev/null 2>&1
     sleep 2
-    #Generate fstab
     genfstab -U /mnt >> /mnt/etc/fstab
 }
 
-# Last Minute Setup Function
-lastMinSetup() {
+function last_MinSetup {
     echo "--------------------------------------"
     print_info "Finishing last minute setup..."
     echo 0 > /proc/sys/kernel/hung_task_timeout_secs
@@ -230,15 +210,16 @@ lastMinSetup() {
     echo ${NEWLINE}
 }
 
-# Main Installation Flow
 main() {
-    greet
-    sleep 1
-    checkNet
-    sleep 1
+    greeter
+    slear
+    check_Net || { log_error "Check your Internet"; exit 1; }
+    slear
     echo "----------------------------"
     print_info "Gathering drives..."
+    echo ${NEWLINE}
     lsblk #TODO: Add something more robust
+    echo ${NEWLINE}
     print_info "Time to select the drive you want too partition..."
     print_info "If you want to manually partition you may, just type exit after mounting /mnt"
     print_info "Otherwise, automated partition will create the standard BIOS/UEFI partitions"
@@ -257,18 +238,17 @@ main() {
         print_info "Modifying $drive..."
         sleep 3
 
-        partition_drive "$drive"
+        partition_Drive "$drive"
     fi
 
-    installer || log_error "Base system installation failed. Exiting."
+    installer || { log_error "Base system installation failed. Exiting."; exit 1; }
 
-    sleep_and_clear
+    slear
     
-    lastMinSetup || log_warning "Last minute setup encountered issues."
+    last_Min_Setup || { log_warning "Last minute setup encountered issues."; exit 1; }
 
     log_success "hArch Installation completed successfully!"
 
 }
 
-# Start the script
 main
